# Generated by Django 4.0 on 2022-02-13 08:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_user', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('displayname_user', models.CharField(blank=True, max_length=200, null=True)),
                ('username_user', models.CharField(blank=True, max_length=200, null=True)),
                ('email_user', models.EmailField(blank=True, max_length=500, null=True)),
                ('country_user', django_countries.fields.CountryField(max_length=2)),
                ('city_user', models.CharField(max_length=100)),
                ('phone_user', models.CharField(max_length=20)),
                ('address_user', models.TextField()),
                ('token_user', models.TextField()),
                ('method_user', models.TextField()),
                ('wishlist_user', models.TextField()),
                ('date_created_user', models.DateTimeField(auto_now_add=True)),
                ('date_updated_user', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
