# Generated by Django 4.0 on 2022-02-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('username_user',), 'verbose_name_plural': 'Users'},
        ),
    ]
