# Generated by Django 4.0 on 2022-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_password_user_users_rol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_user',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
