# Generated by Django 4.0 on 2022-02-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0003_alter_stores_socialnetwork_store'),
        ('orders', '0002_sales'),
        ('accounts', '0004_alter_users_email_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_dispute', models.TextField()),
                ('content_dispute', models.TextField()),
                ('answer_dispute', models.TextField()),
                ('date_created_dispute', models.DateTimeField(auto_now_add=True)),
                ('date_updated_dispute', models.DateTimeField(auto_now=True)),
                ('id_order_dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('receiver_dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.stores')),
                ('transmitter_dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'verbose_name_plural': 'Disputes',
            },
        ),
    ]
