# Generated by Django 4.0 on 2022-02-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commision_sale', models.FloatField(default='0')),
                ('payment_method_sale', models.CharField(max_length=100)),
                ('id_payment_sale', models.CharField(max_length=100)),
                ('status_sale', models.TextField()),
                ('date_created_sale', models.DateTimeField(auto_now_add=True)),
                ('date_updated_sale', models.DateTimeField(auto_now=True)),
                ('id_order_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ('commision_sale',),
            },
        ),
    ]
