# Generated by Django 4.0 on 2022-02-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
                ('titile_list_category', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('image_category', models.ImageField(upload_to='products/categories/%Y/%m/%d, blank=True')),
                ('icon_category', models.ImageField(upload_to='products/categories/icons/%Y/%m/%d, blank=True')),
                ('view_category', models.IntegerField(default='0')),
                ('date_created_category', models.DateTimeField(auto_now_add=True)),
                ('date_updated_category', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name_category',),
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile_list_category', models.CharField(max_length=100)),
                ('name_subcategory', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('image_subcategory', models.ImageField(null=True, upload_to='products/subcategories/%Y/%m/%d, blank=True')),
                ('view_subcategory', models.IntegerField(default='0')),
                ('date_created_subcategory', models.DateTimeField(auto_now_add=True)),
                ('date_updated_subcategory', models.DateTimeField(auto_now=True)),
                ('id_category_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.categories')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ('name_subcategory',),
            },
        ),
    ]
